### ISSUE TITLE
design of list of bookmarks page

### ISSUE THREAD

**Issue by anusharanganathan** [anusharanganathan/colligo#22]
This isn't in the design doc. Should it be similar to manuscript search page?

**Comment by jvine** [comment]
> Should it be similar to manuscript search page?

Yep. 

BTW I note that bookmarking an item on the search page actually refreshes the page and returns you to the top of the page. I don't think that's default blacklight behaviour is it? Compare here:

https://catalyst.library.jhu.edu/catalog?q=cats&search_field=

and here:

https://searchworks.stanford.edu/?utf8=%E2%9C%93&search_field=search&q=cats

**Comment by anusharanganathan** [comment]
commit 01c5f633c.

_Page refreshing when bookmarked_ moved to issue https://github.com/anusharanganathan/colligo/issues/60
