### ISSUE TITLE
Search results: Add remove button (x) on you searched for... in search results

### ISSUE THREAD

**Issue by anusharanganathan** [anusharanganathan/colligo#58]

**Comment by anusharanganathan** [comment]
commit d37fe89

I am currently displaying both the old and the new design - just so it is easy to compare - need to finalize on this

See http://52.24.107.118:5001/catalog?f[manuscript_facet][]=Old+English+Homilies%2C+mostly+by+%C3%86lfric&only_path=true&search_field=transcriptions

**Comment by jvine** [comment]
New design. :+1: 
![screen shot 2016-04-01 at 1 48 48 pm](https://cloud.githubusercontent.com/assets/6945691/14219677/7c8cfb56-f810-11e5-879c-9478062b82a1.png)

**Comment by anusharanganathan** [comment]
commit c052777
Retained new design and removed old design
